version: "3.1"

services:
  db:
    image: postgres
    container_name: demo-postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-posgtres-admin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root

  webapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DB_NAME: demo
      DB_HOST: db
      DB_USER: demo
      DB_PORT: 5432
      DB_PASSWORD: demo
    depends_on:
      - db
volumes:
  pgdata: