name: Django Demo Github Actions

on: [push,pull_request]

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
          POSTGRES_DB: github-actions
        ports:
          - 5432:5432
        options: 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install application dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Check with black 
        uses: piotrpawlaczek/python-blacken@release/stable

      - name: Run migrations
        run: |
          python manage.py migrate
          python manage.py check

      - name: Run tests
        run: python manage.py test
      

  package:
    runs-on: ubuntu-latest
    needs: [health-check-job]
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
