name: Django Demo Github Actions

on: [push,pull_request]

jobs:
  health-check-job:
    runs-on: ubuntu-latest
  
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
          POSTGRES_DB: github-actions
        ports:
          - 5432:5432
        options: 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v2.3.1
          with:
            python-version: 3.10
        - name: Install application dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

  package:
    runs-on: ubuntu-latest
    needs: [health-check-job]
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3


